Job Candidate Review API System/job_profiles/urls.py
from django.urls import path, include
from job_profiles import views
from rest_framework.routers import DefaultRouter
from django.conf import settings
from django.conf.urls.static import static

router = DefaultRouter()
router.register('jobprofiles', views.JobCandidateViewSet)
router.register('applications', views.JobApplicationViewSet)

app_name = 'job_profiles'

urlpatterns = [
    path('login/',views.JobCandidateLoginApiView.as_view()),
    path('job_applications/',views.Job_Applications, name="Job_Applications"),
    path('apply/',views.apply, name="apply"),
    path('',include(router.urls), name="Job_Profile"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Job Candidate Review API System/job_review_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


import job_profiles

urlpatterns = [
    path('admin/', admin.site.urls),
    path('job_apply/', include('job_profiles.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Job Candidate Review API System/job_profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

STATUS_CHOICES = [
    ('Applied', 'Applied'),
    ('Rejected', 'Rejected'),
    ('Shortlisted', 'Shortlisted'),
    ('Accepted', 'Accepted'),
]
# Create your models here.

class JobCandidate(AbstractUser):
    email = models.EmailField("Email Address", unique=True)
    USERNAME_FIELD: 'email'

class JobApplication(models.Model):
    """Job Application"""
    job_profile = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    sop = models.CharField(max_length=250, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    cv = models.FileField(blank=True, null=True, upload_to='uploads/')
    applied_on = models.DateTimeField(auto_now_add=True)

    def __str__ (self):
        return self.job_profile.email

Job Candidate Review API System/job_profiles/views.py
from django.shortcuts import render
from django.http import HttpResponse
from job_profiles import serializers
from job_profiles.models import JobApplication, JobCandidate
from job_profiles import permissions

from rest_framework import viewsets, filters
from rest_framework.authentication import TokenAuthentication
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.settings import api_settings
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer

# Create your views here.
def Test(request):
    return HttpResponse("Something SOment")

class JobCandidateViewSet(viewsets.ModelViewSet):

    serializer_class = serializers.JobCandidateSerializer
    queryset = JobCandidate.objects.all()
    authentication_classes = (TokenAuthentication,)
    permission_classes = (permissions.UpdateOwnProfile,)
    filter_backends = (filters.SearchFilter,)
    search_fields = ('first_name', 'last_name', 'email')

class JobCandidateLoginApiView(ObtainAuthToken):
    renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES


class JobApplicationViewSet(viewsets.ModelViewSet):

    serializer_class = serializers.JobApplicationSerializer
    queryset = JobApplication.objects.all()
    authentication_classes = (TokenAuthentication,)
    permission_classes = (
        permissions.UpdateOwnApplication,
        IsAuthenticatedOrReadOnly,

    )

    def perform_create(self, serializer):
        serializer.save(job_profile=self.request.user)


def Job_Applications (request):
    return render(
        request,
        'index.html'
    )

def apply(request):
    return render(request, 'form.html')

Job Candidate Review API System/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/css/application.css' %}">
    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    <script src="https://kit.fontawesome.com/f784174103.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    
    
</head>
<body>
    {% block main %}
    {% endblock %} 
    <script src="{% static '/js/main2.js' %}"></script>
</body>
</html>

Job Candidate Review API System/templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<div class="container" style="margin-top:50px">
<form onsubmit="post(event)" id="form1">
    <div class="row mb-4">
      <div class="col">
        <div class="form-outline">
            <label class="form-label" for="first_name">First name</label>
          <input type="text" id="first_name" class="form-control" />
        </div>
      </div>
      <div class="col">
        <div class="form-outline">
            <label class="form-label" for="last_name">Last name</label>
          <input type="text" id="last_name" class="form-control" />
        </div>
      </div>
    </div>
  
    <!-- Email input -->
    <div class="form-outline mb-4">
        <label class="form-label" for="email">Email address</label>
      <input type="email" id="email" class="form-control" />
    </div>
  
    <!-- Password input -->
    <div class="form-outline mb-4">
        <label class="form-label" for="password">Password</label>
      <input type="password" id="password" class="form-control" />
    </div>
  
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">Next</button>
  
    <!-- Contact Panel -->
    <div class="text-center">
      <p>Contact Us:</p>
      <button type="button" class="btn btn-primary btn-floating mx-1">
        <i class="fab fa-facebook-f"></i>
      </button>
  
      <button type="button" class="btn btn-primary btn-floating mx-1">
        <i class="fab fa-google"></i>
      </button>
  
      <button type="button" class="btn btn-primary btn-floating mx-1">
        <i class="fab fa-twitter"></i>
      </button>
  
      <button type="button" class="btn btn-primary btn-floating mx-1">
        <i class="fab fa-github"></i>
      </button>
    </div>
  </form>

    <br>
    <form onsubmit="post2(event)" style="display:none" id="form2" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- 2 column grid layout with text inputs for the first and last names -->
        <div class="row mb-4">
        <div class="col">
            <p id="errormessage"></p>
            <div class="form-outline">
                <label class="form-label" for="sop">Statement of Purpose (max 250 characters)</label>
            <textarea type="text" id="sop" class="form-control"  ></textarea>
            </div>
        </div>
        </div>
    
        <!-- File input -->
        <div class="form-outline mb-4">
            <label class="form-label" for="cv">Resume</label>
        <input type="file" id="cv" class="form-control" />
        </div>
    
        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">Submit Application</button>
    
        <!-- Contact Panel -->
        <div class="text-center">
        <p>Contact Us:</p>
        <button type="button" class="btn btn-primary btn-floating mx-1">
            <i class="fab fa-facebook-f"></i>
        </button>
    
        <button type="button" class="btn btn-primary btn-floating mx-1">
            <i class="fab fa-google"></i>
        </button>
    
        <button type="button" class="btn btn-primary btn-floating mx-1">
            <i class="fab fa-twitter"></i>
        </button>
    
        <button type="button" class="btn btn-primary btn-floating mx-1">
            <i class="fab fa-github"></i>
        </button>
        </div>
    </form>
</div>


<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    function post(event){
        event.preventDefault();
        var first_name = document.getElementById('first_name').value;
        var last_name = document.getElementById('last_name').value;
        var email = document.getElementById('email').value;
        var password = document.getElementById('password').value;

        axios.post('/job_apply/jobprofiles/', 
        {
            first_name: first_name,
            last_name: last_name,
            email: email,
            password: password
        },{headers:{"Content-Type" : "application/json"}})
        .then(function (response) {
            // handle success
            console.log(response);
        })
        .catch(function (error) {
            // handle error
            console.log(error.response.data);
        })
        .then(function () {
            document.getElementById('form2').style.display="block";
            document.getElementById('form1').style.display="none";
        });

    }
    function post2(event){
        event.preventDefault();
        var email = document.getElementById('email').value;
        var password = document.getElementById('password').value;
        var sop = document.getElementById('sop').value;
        var cv = document.getElementById('cv').files[0];
        var id;
        var auth;
        //let csrftoken = Cookies.get("csrftoken");
        //let headers = {
        //    "X-CSRFToken": csrftoken,
        //};
        const csrfToken = getCookie('XSRF-TOKEN');
        console.log(csrfToken)
        axios.get('/job_apply/jobprofiles')
        .then(function (response) {
            // handle success
            console.log(response);
            // console.log(response.data[0]);
            for(var i=0;i<response.data.length; i++){
                if(response.data[i].first_name==="") continue;
                if(response.data[i].email===email) id=response.data[i].id;
            }
        })
        .catch(function (error) {
            // handle error
            console.log(error);
        })
        .then(function () {
            var session_url = '/job_apply/login/';
            console.log(email);
            console.log(password);
            var uname = email;
            var pass = password;
            axios.post(session_url, {
                username: uname,
                password: pass                
            }
            ,{ headers: { 
                'X-CSRFToken': csrfToken, 
    
        }}
            ).then(function(response) {
            console.log('Authenticated');
            console.log('id',id);
            console.log(response.data);
            auth = response.data.token;
            console.log(auth)
            }).catch(function(error) {
            console.log("HERE ERROR X")
            console.log(error.response.data);

            })
            .then(function () {
                axios.post('/job_apply/applications/', 
                {
                    job_profile: id,
                    sop: sop,
                    status: "Applied",
                    cv: cv
                },
                {
                    headers: {
                        'Authorization': `Token ${auth}`,
                        'X-CSRFToken': csrfToken, 
                        'Content-Type': 'multipart/form-data'
                    }
                })
                .then(function (response) {
                    // handle success
                    console.log(response);


                })
                .catch(function (error) {
                    // handle error
                    console.log(error.response.data);
                    document.getElementById('errormessage').innerHTML = error.response;
                })
                .then(function () {
                    location.reload();
                });
            });
        })

    }

</script>
{% endblock %}

Job Candidate Review API System/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Avaiate | Job Review System {% endblock %}

{% block main %}
<style>
.viewsApplicationsBtn {
    position: absolute    ;
    top: 80px;
    right: 10px;
    color: white;
    background-color: #254292;
    padding: 10px;
    border-radius: 5px;
    transition: all 0.5s;
}

.viewsApplicationsBtn:hover {
    filter: brightness(80%);
}
    
@media screen and (max-width: 600px){
.viewsApplicationsBtn {
    position: absolute;
    top: 50px;
    font-size: 14px;
    right: 10px;
    color: white;
    background-color: #254292;
    padding: 10px;
    border-radius: 5px;
    transition: all 0.5s;
    }
}
</style>
<div  style="margin-left:auto !important; margin-right:auto !important; display:flex; justify-content:center">
<button onclick="get(event)">GET APPLICANTS</button>&nbsp;
<button><a href="{% url 'job_profiles:apply' %}">CREATE NEW APPLICATION</a></button></div>

<div class="section__projects" id="maincontainer" style="margin-left:auto; margin-right:auto">
    <div id="repeat">
    <div class="section__projectCard is-collapsed">
        <div class="section__projectCardInner" style="height: 325px !important;">
            <p class="section__projectCardTitle" id="fullname"></p>
            <p class="section__projectCardSecondaryText" id="email"></p>
            <p class="section__projectCardMode"><b>Status:</b> <span id="status"></span></p>
            <p class="section__projectCardDetail"></p>
            <p class="section__projectCardSubtitle" style="margin-top: 10px;">Applied On: <span id="applied_on"></span></p>
            <p class="section__projectCardAction js-expander">Read more</p>
        </div>
        <div class="section__projectDetails">
            <i class="fa fa-close js-collapser"></i>
            <h1 style="margin-bottom: 20px;">Candidate Details</h1>
            <div class="section__projectInfo" style="flex:1;">
                <div class="section__projectInfo-sub">
                    <p><b><i class=" fas fa-file-signature"></i></i>Name: </b><span id="fullname2"></span></p>
               
                    <p><b><i class="fas fa-university"></i></i>University: </b><span></span></p>
                    <p><b><i class="fas fa-calendar-day"></i></i>Applied On: </b><span id="applied_on2"></span></p>
                </div>
                <div class="section__projectInfo-sub">
                    <p><b><i class="fas fa-calendar-alt"></i></i>Email: </b><span id="email2"></span>
                    </p>
                    <p><b><i class="fas fa-dollar-sign"></i>Status: </b><span id="status2"></span></p>
                    <form style="display:none" class="status_form" onsubmit="patch(event)">
                        <label for="status_change"><p>Choose Status: </p></label>
                        <select id="status_change" class="status_change" name="status_change">
                            <option value="Applied">Applied</option>
                            <option value="Shortlisted">Shortlisted</option>
                            <option value="Rejected">Rejected</option>
                            <option value="Accepted">Accepted</option>
                        </select>
                        <input type="hidden" id="status_email">
                        <input type="hidden" id="status_password">
                        <input type="hidden" class="status_id" id="status_id">
                        <input type="hidden" id="no_of_app">
                        <button type="submit">Change</button>
                    </form>
                </div>
            </div>
            <p class="section__projectDetails2" style="flex-direction: column;"><b><i
                        class="fas fa-info-circle"></i>SOP: <p id="sop"></p>
                </b><br><br> <span><b>Files: </b></span><span></span></p>
            <p><b><i class="fas fa-puzzle-piece"></i>Resume: <a id="cv" download>Download</a>
                </b><span></span></p>
                <button onclick="openstatus(event)">Change Status</button>
        </div>

</div>
</div>
</div>

<a style="display:none;" href="{% url 'job_profiles:Job_Applications' %}" id="reloader"></a> 
<script>
    function openstatus(event) {
        event.preventDefault();
        let x = document.getElementsByClassName('status_form');
        console.log(x);
        for(let y in x){
            document.getElementsByClassName('status_form')[y].style.display="block";
        }
    }

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    function get(event){
    event.preventDefault();
    var divrepeat = document.getElementById("repeat"), container = document.getElementById("maincontainer");
    // Make a request for a user with a given ID
    axios.get('/job_apply/applications')
    .then(async function (response) {
        // handle success

        let length = response.data.length;
        let sop = [], status = [];
        let cv = [];
        let applied_on = [];
        let j=0;
        let application_ids = [];
        for(var i=0;i<response.data.length; i++){
            event.preventDefault();
            sop[i]=response.data[i].sop;
            cv[i]=response.data[i].cv;
            status[i]=response.data[i].status;
            application_ids[i] = response.data[i].id;
            applied_on[i] = response.data[i].applied_on.substring(0,10);
            await axios.get(`/job_apply/jobprofiles/${response.data[i].job_profile}/`)
            .then(function(secondresponse) {
                    //console.log(secondresponse.data);
                    document.getElementById('fullname').innerHTML = secondresponse.data.first_name + " " + secondresponse.data.last_name;
                    document.getElementById('fullname2').innerHTML = secondresponse.data.first_name + " " + secondresponse.data.last_name;
                    document.getElementById('email').innerHTML = secondresponse.data.email;
                    document.getElementById('email2').innerHTML = secondresponse.data.email;
                    document.getElementById('cv').href = cv[j];
                    document.getElementById('applied_on').innerHTML = applied_on[j];
                    document.getElementById('applied_on2').innerHTML = applied_on[j];
                    document.getElementById('status').innerHTML = status[j];
                    document.getElementById('status2').innerHTML = status[j];
                    
                    document.getElementById('status_email').value = secondresponse.data.email;
                    document.getElementById('status_password').value = secondresponse.data.password;
                    document.getElementById('status_id').value = application_ids[j];
                    document.getElementById('sop').innerHTML = sop[j++];
                    document.getElementById('no_of_app').value = length;

                    if(j<length){
                        let clone = divrepeat.cloneNode(true);
                        container.appendChild(clone);

                        let projectCards = Array.from(document.getElementsByClassName("section__projectCard"));
                        //console.log(document.getElementsByClassName("section__projectCard"));
                        let projectCardTimeout;
                        let isOtherProjectOpen = false;
                        projectCards.map(projectCard => {
                            projectCard.querySelector(".js-expander").addEventListener("click", () => {
                                if (projectCard.classList.contains("is-collapsed")) {
                                    projectCards.map(projectCard => {
                                        projectCard.classList.remove("is-expanded");
                                        projectCard.classList.add("is-collapsed");
                                        projectCard.style.zIndex = 0;
                                    });
                                    clearTimeout(projectCardTimeout);
                                    projectCardTimeout = setTimeout(() => {
                                        projectCard.classList.remove("is-collapsed");
                                        projectCard.classList.add("is-expanded");
                                        projectCard.style.zIndex = 1;
                                        window.scrollTo(0, projectCard.offsetTop + 150);
                                    }, isOtherProjectOpen ? 300 : 0);

                                    // switch isOtherProjectOpen
                                    isOtherProjectOpen = true;
                                }
                                else {
                                    projectCard.classList.remove("is-expanded");
                                    projectCard.classList.add("is-collapsed");
                                    projectCard.style.zIndex = 0;
                                    window.scrollTo(0, projectCard.offsetTop - 200);
                                    isOtherProjectOpen = false;
                                }
                            });

                            projectCard.querySelector(".js-collapser").addEventListener("click", () => {
                                projectCard.classList.remove("is-expanded");
                                projectCard.classList.add("is-collapsed");
                                projectCard.style.zIndex = 0;
                                window.scrollTo(0, projectCard.offsetTop - 200);
                                isOtherProjectOpen = false;
                            });
                        });

                    }
            })
        }
        
    })
    .catch(function (error) {
        // handle error
        console.log(error.response.data);
    })
    .then(function () {
  
    })
    
}

    function patch(event) {
        event.preventDefault();
        const csrfToken = getCookie('XSRF-TOKEN');
        console.log(csrfToken)
        let email = document.getElementById('status_email').value;
        let password = document.getElementById('status_password').value;
        let job_profileid = document.getElementById('status_id').value;
        console.log("WOW",email,"Passwrod",password);
        console.log(status);
        var session_url = '/job_apply/login/';
        var uname = email;
        var pass = password;
        axios.post(session_url, {
            username: 'nk@gmail.com',     //Add SuperUser credentials here so that he/she can edit any job applications he/she wants
            password: '1234',            
        }
        ,{ headers: { 
            'X-CSRFToken': csrfToken, 
        }}
        ).then(async function(response) {

            console.log('Authenticated');
            auth = response.data.token;
            let no_of_app = document.getElementById('no_of_app').value;
            for(let p=0;p<no_of_app;p++){
                let app_id = document.getElementsByClassName('status_id')[p].value;
                let statuschange = document.getElementsByClassName('status_change')[p].value;
                await axios.patch(`/job_apply/applications/${app_id}/`,
                    {  
                        status: statuschange
                },
                    { headers: { 
                        'Authorization': `Token ${auth}`,
                        'X-CSRFToken': csrfToken, 
            
                }}
                ).then((response) => {
                    console.log(response.data);
                    console.log("Check if changed");

                }).catch((error) => {
                    console.log("last error: ",error.response.data);
                })

            }
        }).then(function () {
                    
            document.getElementById('reloader').click();
        });
    }

</script>
{% endblock %}

Job Candidate Review API System/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

</head>
<body>
    <h2 id="pop"></h2>
    {% for applicant in applicants %}
    {{applicant.sop}}
    <h3>Sup</h3>
    {% endfor %}
    <button onclick="get()">GET</button>
    <button onclick="post()">POST</button>
</body>
 <!-- <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script> --> 
<script>
    function get(){
        // Make a request for a user with a given ID
        var t= "";
        axios.get('/job_apply/jobprofiles')
        //axios.get('/job_apply/applications')
        .then(function (response) {
            // handle success
            console.log(response);
            // console.log(response.data[0]);
            for(var i=0;i<response.data.length; i++){
                console.log(response.data[i]);
                 t+=response.data[i].email+" ";
            }
            document.getElementById('pop').innerHTML = t;
        })
        .catch(function (error) {
            // handle error
            console.log(error);
        })
        .then(function () {
            // always executed
        })
    }
    function post(){
        axios.post('/job_apply/jobprofiles/', 
        {
            first_name: "vinod",
            last_name: "raj",
            email: "vinodraj@gmail.com",
            password: "vinodmeena"
        },{headers:{"Content-Type" : "application/json"}})
        //     axios.post(
        // 'https://reqres.in/api/register',
        // {
        //     email: 'eve.holt@reqres.in',
        //     password: 'pistol'
        // })
        .then(function (response) {
            // handle success
            console.log(response);
        })
        .catch(function (error) {
            // handle error
            console.log(error.response.data);
        })
        .then(function () {
            // always executed
        });
    }

</script>
</html>